name: â„ï¸ Lint

on: [pull_request]

jobs:
  yamllint:
    name: ğŸº YAML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ğŸ§¹ YAML Lint
<<<<<<< HEAD
        uses: ibiqlik/action-yamllint@v3
=======
        uses: github/super-linter@v3
        env:
          VALIDATE_YAML: true
          FILTER_REGEX_INCLUDE: .*\.github/.*
>>>>>>> master
